task:
    name: ubport
    timeout_in: 120m 
    container:
      image: ubuntu:20.04
      cpu: 8  
      memory: 32G 
    mkdir: 
      - cd && mkdir -p /build/bin && mkdir -p /build/sources && echo export PATH=\$PATH:\/build/bin >> /root/.bashrc
    pkgupdate: 
      - apt-get update && dpkg --add-architecture i386 && apt update && apt install git gnupg flex bison gperf build-essential zip bzr curl libc6-dev libncurses5-dev:i386 x11proto-core-dev libx11-dev:i386 libreadline6-dev:i386 libgl1-mesa-glx:i386 libgl1-mesa-dev g++-multilib mingw-w64-i686-dev tofrodos python3-markdown libxml2-utils xsltproc zlib1g-dev:i386 schedtool liblz4-tool bc lzop imagemagick libncurses5 rsync python-is-python3 python2
    bin: 
      - cd && mkdir -p ~/bin && echo export PATH=\$PATH:\$HOME/bin >> ~/.bashrc && source ~/.bashrc
    repo:
      - curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+rx ~/bin/repo
    

      
